OIR, CPU discovery and event handler integration
intelsdi-x/kubernetes pull request #32
Opened 2017-04-03 13:24 UTC by squall0gd

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2017-04-03 20:48 UTC, ConnorDoyle reviewed
Overall LGTM, some minor review comments

2017-04-03 20:48 UTC, ConnorDoyle commented on cluster/addons/iso-client/coreaffinity-isolator.go
> +func handleSIGTERM(sigterm chan os.Signal, client *aff.EventDispatcherClient, opaque *opaq.OpaqueIntegerResourceAdvertiser) {
Could we rename this to `shutdownIsolator` or similar and call this from the TERM handler? There are a number of control flow paths in which we need to both unregister and unadvertise the OIRs (e.g. every instance of `glog.Fatalf(...)`).

2017-04-03 20:48 UTC, ConnorDoyle commented on cluster/addons/iso-client/coreaffinity-isolator.go
>  		glog.Fatalf("Cannot register isolator: %v", err)
Make sure to unadvertise OIRs before dying.

2017-04-03 20:48 UTC, ConnorDoyle commented on cluster/addons/iso-client/coreaffinity/isolator.go
> +
Please kill this blank line.

2017-04-03 20:48 UTC, ConnorDoyle commented on cluster/addons/iso-client/coreaffinity/isolator.go
> +func (i *isolator) countCoresFromOIR(pod *v1.Pod, cgroupInfo *lifecycle.CgroupInfo) int64 {
Can we drop the `cgroupInfo` parameter? Doesn't appear to be used within the function body.

2017-04-03 20:48 UTC, ConnorDoyle commented on cluster/addons/iso-client/coreaffinity/isolator.go
> +func (i *isolator) eventReplyGenerator(error string, cgroupInfo *lifecycle.CgroupInfo, cgropupResources []*lifecycle.CgroupResource) *lifecycle.EventReply {
Is this function necessary?

2017-04-03 20:48 UTC, ConnorDoyle commented on cluster/addons/iso-client/coreaffinity/isolator.go
> +func (i *isolator) eventReplyGenerator(error string, cgroupInfo *lifecycle.CgroupInfo, cgropupResources []*lifecycle.CgroupResource) *lifecycle.EventReply {
If you decide to keep it, could we rename to `generateEventReply`?

2017-04-03 20:48 UTC, ConnorDoyle commented on cluster/addons/iso-client/coreaffinity/isolator.go
> +func (i *isolator) reserveCores(cores int64) ([]int, error) {
General comment: we should be consistent in terminology across the code w.r.t. CPUs vs cores. Proposal: `cpu` should always mean logical CPUs as reported by the operating system, `core` should always mean a physical core (possibly hosting two hyperthreads).

2017-04-03 20:48 UTC, ConnorDoyle commented on cluster/addons/iso-client/coreaffinity/isolator.go
> +func (i *isolator) reserveCores(cores int64) ([]int, error) {
Otherwise this is kind of confusing to read.

2017-04-03 20:48 UTC, ConnorDoyle commented on cluster/addons/iso-client/coreaffinity/isolator.go
> +func parseCorse(cores []int) string {
s/parseCorse/parseCores

2017-04-03 20:48 UTC, ConnorDoyle commented on cluster/addons/iso-client/coreaffinity/isolator.go
> +func parseCorse(cores []int) string {
Also, this looks like the opposite of "parse". Maybe rename this `asCPUList` or similar?

2017-04-03 20:48 UTC, ConnorDoyle commented on cluster/addons/iso-client/cputopology/cpu.go
> +func (c *CPUTopology) GetCpusNum() int {
s/GetCpusNum/GetNumCPUs

2017-04-03 20:48 UTC, ConnorDoyle commented on cluster/addons/iso-client/cputopology/cpu.go
> +func (c *CPUTopology) GetCpusNum() int {
Or, GetTotalCPUs (in contrast to GetAvailableCPUs below)

2017-04-03 23:30 UTC, squall0gd commented
@ConnorDoyle Thanks a lot for your review!

2017-04-04 14:45 UTC, ConnorDoyle requested changes

2017-04-04 14:45 UTC, ConnorDoyle commented on cluster/addons/iso-client/coreaffinity-isolator.go
> +	glog.Infof("Unregistering custom-isolator: %s", name)
Want to log this before the call to `Unregister`?

2017-04-04 14:45 UTC, ConnorDoyle commented on cluster/addons/iso-client/coreaffinity-isolator.go
>  	//	"k8s.io/apimachinery/pkg/util/uuid"
Can we ditch these commented-out lines?

2017-04-04 14:45 UTC, ConnorDoyle commented on cluster/addons/iso-client/coreaffinity-isolator.go
> +	if err := opaque.RemoveOpaqueResource(); err != nil {
Could we log before attempting to remove the opaque resource? (e.g. "Removing opaque resource %s from node %s")

2017-04-04 14:45 UTC, ConnorDoyle commented on cluster/addons/iso-client/coreaffinity-isolator.go
> +		glog.Fatalf("Cannot create opaque resource advertiser: %v", err)
Unreachable code (`shutdownIsolator` not expected to return) -- log at error level prior to `shutdownIsolator` call?

2017-04-04 14:45 UTC, ConnorDoyle commented on cluster/addons/iso-client/coreaffinity-isolator.go
> +		glog.Fatalf("Failed to advertise opaque resources: %v", err)
Unreachable code (`shutdownIsolator` not expected to return) -- log at error level prior to `shutdownIsolator` call?

2017-04-04 14:45 UTC, ConnorDoyle commented on cluster/addons/iso-client/coreaffinity-isolator.go
>  		glog.Fatalf("Cannot create eventDispatcherClient: %v", err)
Unreachable code (`shutdownIsolator` not expected to return) -- log at error level prior to `shutdownIsolator` call?

2017-04-04 14:45 UTC, ConnorDoyle commented on cluster/addons/iso-client/coreaffinity-isolator.go
>  		glog.Fatalf("Failed to register isolator: %v . Reply: %v", err, reply)
Unreachable code (`shutdownIsolator` not expected to return) -- log at error level prior to `shutdownIsolator` call?

2017-04-04 15:10 UTC, ConnorDoyle approved these changes

2017-04-04 15:10 UTC, ConnorDoyle commented
👍

2017-04-04 18:46 UTC, merged