Client label node
intelsdi-x/kubernetes pull request #40
Opened 2017-04-07 14:17 UTC by squall0gd

This is proposal of node labeling implementation from client side. I'm going to prepare second implementation from kubelet side.

2017-04-12 09:12 UTC, flyingcougar requested changes

2017-04-12 09:12 UTC, flyingcougar commented on cluster/addons/iso-client/coreaffinity-isolator.go
> +		glog.Fatalf("cannot unset label from node: %q", err)
"Failed to"

2017-04-12 09:12 UTC, flyingcougar commented on cluster/addons/iso-client/coreaffinity-isolator.go
> +		glog.Errorf("cannot mark node: %q", err.Error())
"Failed to label node ...."

2017-04-12 09:12 UTC, flyingcougar commented on cluster/addons/iso-client/coreaffinity-isolator.go
> +	glog.Infof("Mark node that isolator %q is available", name)
s/Mark/Label

2017-04-12 09:12 UTC, flyingcougar commented on cluster/addons/iso-client/utils/labels.go
> +func SetLabel(isolatorName string) error {
very user friendly wrap :+1:

2017-04-12 09:12 UTC, flyingcougar commented on cluster/addons/iso-client/utils/labels.go
> +		return fmt.Errorf("cannot get in-cluster config: %q", err)
"Failed to get in-cluster config"

2017-04-12 09:12 UTC, flyingcougar commented on cluster/addons/iso-client/utils/labels.go
> +		return fmt.Errorf("cannot gather hostname: %q", err)
"Failed to read hostname"

2017-04-12 09:12 UTC, flyingcougar commented on cluster/addons/iso-client/utils/labels.go
> +		return fmt.Errorf("cannot achieve client instance for Kubernetes: %s", err)
"Failed to connect initialize client connection" or sth simmilar

2017-04-12 09:12 UTC, flyingcougar commented on cluster/addons/iso-client/utils/labels.go
> +		return fmt.Errorf("cannot get node %q: %q", nodename, err)
"Failed to"....

2017-04-12 09:12 UTC, flyingcougar commented on cluster/addons/iso-client/utils/labels.go
> +		delete(labels, isolatorName)
what will happen if the label has meed deleted manually by user and then `delete(labels, isolatorName)` is called ? error, exception ?

2017-04-12 09:15 UTC, squall0gd commented on cluster/addons/iso-client/utils/labels.go
> +		delete(labels, isolatorName)
https://golang.org/pkg/builtin/#delete

2017-04-12 21:18 UTC, ConnorDoyle commented
Are we dropping this PR in favor of #41?

2017-04-13 11:49 UTC, flyingcougar commented
@ConnorDoyle - i'd agree that we should drop this in favor of #41

2017-04-13 11:55 UTC, closed without merging