Kubelet label node
intelsdi-x/kubernetes pull request #41
Opened 2017-04-10 16:02 UTC by squall0gd

2017-04-11 05:45 UTC, ConnorDoyle commented on cmd/kubelet/app/server.go
> +	kubeClient, err := getKubeClient(s)
Is it possible to hook into the existing sync loop? That code already rewrites the node status based on resource info from cadvisor and OIRs.

Also looking forward to enabling operator-unregistration, we would need to get access to the updated (read) status in that sync anyway.

2017-04-11 05:45 UTC, ConnorDoyle commented on cmd/kubelet/app/server.go
> +	kubeClient, err := getKubeClient(s)
One way (just a suggestion) could be to add an API in the event dispatcher to get a list of currently registered isolators, and then call that from inside the sync loop.

2017-04-11 05:45 UTC, ConnorDoyle commented on cmd/kubelet/app/server.go
> +	kubeClient, err := getKubeClient(s)
Trade off would be that instead of plumbing the client down as done here, we would have to surface the event dispatcher by plumbing it up to here.

2017-04-11 05:45 UTC, ConnorDoyle commented on cmd/kubelet/app/server.go
> +	kubeClient, err := getKubeClient(s)
Besides possibly making the next step a little easier, an advantage to piggybacking on the sync is that a misbehaving isolator in this impl could cause the Kubelet to spam the API server with node status updates.

2017-04-12 11:56 UTC, flyingcougar commented
I like the concept with channel passed to `syncLoopIteration`.

2017-04-12 12:14 UTC, flyingcougar requested changes

2017-04-12 12:14 UTC, flyingcougar commented on pkg/kubelet/kubelet.go
> +	kl.eventDispacherEventChannel = pcm.GetEventDispatcherChan()
This will be called every time we have pod update. IMHO it'd be great if we could set 
`kl.eventDispacherEventChannel` once since we dont expect it to change right ?
In any case since this is PoC we can do `if kl.eventDispacherEventChannel  not nil` or `Do.Once`

2017-04-12 21:12 UTC, ConnorDoyle approved these changes
Overall this looks pretty great! Minor comments, mostly just wording suggestions. Now I see what @flyingcougar meant about creating the event dispatcher higher up and then passing it down to the pod container manager. Let's still explore that in a follow-up.

2017-04-12 21:12 UTC, ConnorDoyle commented on pkg/kubelet/cm/event_dispatcher.go
> +	GetEventChannelNotificator() chan EventDispatcherEvent
nit: s/GetEventChannelNotificator/GetEventChannel

2017-04-12 21:12 UTC, ConnorDoyle commented on pkg/kubelet/cm/event_dispatcher.go
> +	UPDATE_ISOLATOR_LIST EventDispatcherEventType = iota
nit: s/UPDATE_ISOLATOR_LIST/ISOLATOR_LIST_CHANGED ?
Rationale: update is what you want the recipient to do, but list-changed is what happened (the event)

2017-04-12 21:12 UTC, ConnorDoyle commented on pkg/kubelet/cm/event_dispatcher.go
> +	notifyChannel chan EventDispatcherEvent
s/notifyChannel/eventChannel ?

2017-04-12 21:12 UTC, ConnorDoyle commented on pkg/kubelet/cm/event_dispatcher.go
> +	var isolators []string
nit: Since the length is known, could construct the slice with `make([]string, len(ed.isolators))`

2017-04-12 21:12 UTC, ConnorDoyle commented on pkg/kubelet/kubelet.go
> +				glog.Errorf("cannot achieve node: %q", err.Error())
How about "update isolator list: unable to get current node"?

2017-04-12 21:12 UTC, ConnorDoyle commented on pkg/kubelet/kubelet.go
> +				node.ObjectMeta.Labels["external-isolators"] = eventDispatcherEvent.Body
label will probably need to be something like "node.alpha.kubernetes.io/registered-isolators". let's make a const for this.

2017-04-12 21:12 UTC, ConnorDoyle commented on pkg/kubelet/kubelet.go
> +				glog.Errorf("cannot update node information: %q", err.Error())
Suggestion to add context: "unable to update list of registered isolators in node: %q"

2017-04-12 21:13 UTC, ConnorDoyle commented
Needs rebase (updated the base branch to correspond w/ upstream master)

2017-04-14 13:14 UTC, flyingcougar requested changes

2017-04-14 13:14 UTC, flyingcougar commented on pkg/kubelet/cm/pod_container_manager_linux.go
> +	return m.eventDispatcher.GetEventChannel()
if `cgrous-per-qos` flag is false (or future flag used to enable ext-iso) then there is no `m.eventDispatcher` object present

2017-04-14 14:24 UTC, flyingcougar requested changes

2017-04-14 14:24 UTC, flyingcougar commented on pkg/kubelet/cm/event_dispatcher.go
> +	for isolator := range ed.isolators {
consiger using:
 keys := reflect.ValueOf(ed.isolators).MapKeys()
no loop needed

2017-04-18 10:23 UTC, squall0gd commented on pkg/kubelet/cm/event_dispatcher.go
> +	for isolator := range ed.isolators {
output from `MapKeys()` is `[]reflect.Value`. You cannot cast it directly to `[]string` so you need to create another loop. This loop will iterate through each element of `[]reflect.Value`, cast it to `string` and append to `[]string`.

2017-04-19 10:56 UTC, flyingcougar approved these changes

2017-04-19 10:56 UTC, flyingcougar commented on pkg/kubelet/cm/event_dispatcher.go
> +	for isolator := range ed.isolators {
ok

2017-04-19 14:54 UTC, merged