Unit tests for EventDispatcher
intelsdi-x/kubernetes pull request #49
Opened 2017-04-19 16:13 UTC by squall0gd

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2017-04-19 16:16 UTC, squall0gd commented
Current coverage ~89%

2017-04-20 13:24 UTC, flyingcougar requested changes

2017-04-20 13:24 UTC, flyingcougar commented on pkg/kubelet/cm/event_dispatcher.go
> +	fmt.Println(lis.Addr().String())
:) please remove

2017-04-20 14:05 UTC, flyingcougar requested changes

2017-04-20 14:05 UTC, flyingcougar commented on pkg/kubelet/cm/event_dispatcher_test.go
> +					registeredIsolator,
add check for socket/name correlation corectness

2017-04-20 14:05 UTC, flyingcougar commented on pkg/kubelet/cm/event_dispatcher_test.go
> +		ed := newEventDispatcher()
here is inside for loop, in test case above outside, please be consistent

2017-04-20 14:05 UTC, flyingcougar commented on pkg/kubelet/cm/event_dispatcher_test.go
> +		go getIsolators(ed.GetEventChannel(), &event)
please also check for event

2017-04-20 14:05 UTC, flyingcougar commented on pkg/kubelet/cm/event_dispatcher_test.go
> +type dummy struct {
s/dummy/`sth else`

2017-04-20 14:05 UTC, flyingcougar commented on pkg/kubelet/cm/event_dispatcher_test.go
> +		server.ResetDummyObject()
please rename ResetDummyObject

2017-04-20 14:05 UTC, flyingcougar commented on pkg/kubelet/cm/event_dispatcher_test.go
> +			if eventReply.Error != "" {
please add comment on that case

2017-04-20 14:05 UTC, flyingcougar commented on pkg/kubelet/cm/event_dispatcher_test.go
> +			if !strings.Contains(err.Error(), testCase.serverError.Error()) {
please add comment on that case

2017-04-20 14:05 UTC, flyingcougar commented on pkg/kubelet/cm/event_dispatcher_test.go
> +		if err != nil {
please add comment on that case

2017-04-20 14:05 UTC, flyingcougar commented on pkg/kubelet/cm/event_dispatcher_test.go
> +		er := &lifecycle.EventReply{
please rename to sth else, more descriptive

2017-04-20 14:05 UTC, flyingcougar commented on pkg/kubelet/cm/event_dispatcher_test.go
> +		case lifecycle.IsolationControl_CGROUP_CPUSET_CPUS:
to consider: instead doing `switch case` here, adjust the `testCases` to consist of output from isolators and expected `ResourceConfig`. the in the loop you just need to compare those. The advantage is that adding new test cases involves only appending to `testCase` structure.

2017-04-20 14:05 UTC, flyingcougar commented on pkg/kubelet/cm/event_dispatcher_test.go
> +	testCases := []struct {
i.e. s/testCase/testResourceConfig
sth more descriptive

2017-04-21 12:42 UTC, squall0gd commented on pkg/kubelet/cm/event_dispatcher_test.go
> +					registeredIsolator,
done

2017-04-21 12:45 UTC, squall0gd commented on pkg/kubelet/cm/event_dispatcher_test.go
> +		go getIsolators(ed.GetEventChannel(), &event)
done

2017-04-21 12:46 UTC, squall0gd commented on pkg/kubelet/cm/event_dispatcher_test.go
> +		ed := newEventDispatcher()
done

2017-04-21 12:48 UTC, squall0gd commented on pkg/kubelet/cm/event_dispatcher_test.go
> +type dummy struct {
done

2017-04-21 12:48 UTC, squall0gd commented on pkg/kubelet/cm/event_dispatcher_test.go
> +		server.ResetDummyObject()
done

2017-04-21 12:51 UTC, squall0gd commented on pkg/kubelet/cm/event_dispatcher_test.go
> +			if !strings.Contains(err.Error(), testCase.serverError.Error()) {
done

2017-04-21 12:52 UTC, squall0gd commented on pkg/kubelet/cm/event_dispatcher_test.go
> +			if eventReply.Error != "" {
done

2017-04-21 12:56 UTC, squall0gd commented on pkg/kubelet/cm/event_dispatcher_test.go
> +	testCases := []struct {
Disagree. Let's be consistent with Kubernetes

2017-04-21 12:57 UTC, squall0gd commented on pkg/kubelet/cm/event_dispatcher_test.go
> +		er := &lifecycle.EventReply{
done

2017-04-24 13:05 UTC, squall0gd commented
Current coverage > 90%

2017-04-24 14:18 UTC, flyingcougar commented
lgtm from me, please check if tests with master branch.

2017-04-24 14:47 UTC, ConnorDoyle reviewed
Please squash to 1 commit before merging

2017-04-24 15:22 UTC, merged