Add Hugepage-Isolator
intelsdi-x/kubernetes pull request #58
Opened 2017-04-28 14:36 UTC by swatisehgal

+ support for Hugetlbfs Cgroup in Kubelet

Co-Authored-By: Louise Daly louise.m.daly@intel.com

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2017-04-28 19:38 UTC, ConnorDoyle requested changes
Could you please remove the following from the patch?

* Duplicated isolator library files (import the existing one instead?)
* The hugepage-isolator executable (also add to .gitignore in that directory)

2017-05-02 13:15 UTC, lmdaly commented
Hey @ConnorDoyle made those changes. Thanks for the review!

2017-05-04 10:38 UTC, squall0gd commented on cluster/addons/hp-client/examples/example-hugepage-pod.yaml
> +    image: si-docker.ir.intel.com/ssehgal/mmap
Is this image is visible/available outside of Intel? As far as we want to upstream it, community won't be able to use your example ;)

2017-05-04 10:38 UTC, squall0gd commented on cluster/addons/hp-client/examples/example-hugepage-pod.yaml
> +    args: [ "while true; do sleep 300000; done;" ]
You can prepare your image like this:
```docker
...
ENTRYPOINT ["/bin/bash", "-c", "--", "sleep"]
CMD "inf"
```

Your will be able run this image w/o any command and args. If you need to change amount of time, then you can do it with command, by passing time like this:

```yaml
    command: 300
```

2017-05-04 10:38 UTC, squall0gd commented on cluster/addons/hp-client/examples/hugepage-client.yaml
> +        image: si-docker.ir.intel.com/lmdaly/cgroup-hugepage-isolator
It's better to use `cgroup-hugepage-isolator` here(which is declared in Dockerfile)

2017-05-04 10:38 UTC, squall0gd commented on cluster/addons/hp-client/hugepages/discovery/hp_discovery.go
> +
remove this line

2017-05-04 10:38 UTC, squall0gd commented on cluster/addons/hp-client/hugepage-isolator.go
> +// TODO: split it to smaller functions
is it still valid?

2017-05-04 10:38 UTC, squall0gd commented on cluster/addons/hp-client/hugepage-isolator.go
> +	isolatorLocalAddress = "localhost:5444"
Can you change your `isolatorLocalAddress` to sth different? It will overlapping with already existing `coreaffinity` isolator.

2017-05-04 10:38 UTC, squall0gd commented on cluster/addons/hp-client/hugepages/discovery/hp_discovery.go
> +        procFsPath := "/proc/sys/vm/nr_hugepages"
s/procFsPath/hugepageInfoPath/

2017-05-04 10:38 UTC, squall0gd commented on cluster/addons/hp-client/hugepages/hpIsolator.go
> +		}
you can move annotations parsing to another function, so each of your function will be responsible for one task :)

2017-05-04 10:38 UTC, squall0gd commented on cluster/addons/hp-client/hugepages/hpIsolator.go
> +	return cgroupResource, nil
probably you should split logic here to other functions.

2017-05-09 11:46 UTC, closed without merging