Reorganized example isolators.
intelsdi-x/kubernetes pull request #59
Opened 2017-04-30 23:04 UTC by ConnorDoyle

- Update OIR lib to get node name from env.

2017-04-30 23:05 UTC, ConnorDoyle commented
Updated during demo prep

2017-04-30 23:16 UTC, ConnorDoyle commented
Demo docs (wip): https://gist.github.com/ConnorDoyle/ddfa508473de5c77a0fc931b13f1ff49

2017-05-02 09:49 UTC, squall0gd commented on cluster/addons/iso-client/examples/cpuset-visualizer-0.yaml
> +apiVersion: v1
Add kubernetes header and information about purpose of this file.

2017-05-02 09:49 UTC, squall0gd commented on cluster/addons/iso-client/examples/cpuset-visualizer-1.yaml
> +apiVersion: v1
Add kubernetes header and information about purpose of this file.

2017-05-02 09:49 UTC, squall0gd commented on cluster/addons/iso-client/examples/cpuset-visualizer-2.yaml
> +apiVersion: v1
Add kubernetes header and information about purpose of this file.

2017-05-04 12:13 UTC, flyingcougar commented
lgtm - i was thinking about approach with go lang `pkg/` and `src/` but in general this one seems easier and cleaner (less "directory" overhead)

2017-05-04 12:14 UTC, flyingcougar requested changes
Should we have `Makefile` and `Dockerfile` for noop as well ?

2017-05-09 11:46 UTC, closed without merging